baseURL = "http://example.org/"
languageCode = "es-AR"
title = "Programación Avanzada con Objetos"

theme = "minimo"

# custom folders
staticDir = ["public", "static"]
publishDir = "dist"  # to avoid collision with search-index :(

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
enableEmoji = true

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "02 Jan 2006"
listDateFormat = "02 Jan 2006"
archiveDateFormat = "02 Jan"
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[sidebar_menu]
title = 'Side bar'

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","taxonomy_cloud"]

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[params.assets]
customCSS = ["custom.css"]

[[menu.main]]
name = "Home"
weight = 1
identifier = "home"
url = "/"


